object Versions {
    const val android = "7.2.2"
    const val kotlin = "1.7.10"
    const val kotlinJson = "1.0.1"
    const val appcompat = "1.5.1"
    const val compose = "1.2.1"
    const val composeCompiler = "1.3.1"
    const val composeActivity = "1.6.0"
    const val composeViewModel = "2.5.1"
    const val material = "1.0.0-beta03"
    const val runtimeKtx = "2.5.1"
    const val ktor = "2.1.2"
    const val chuck = "1.1.0"
    const val gson = "2.8.8"
    const val coil = "2.2.2" //glide
    const val napier = "2.6.1"
    const val junit = "4.13.2"
    const val junitExt = "1.1.3"
    const val espresso = "3.4.0"
}